### ISSUE TITLE
非常感谢您的工作！有一个opt参数问题想向您咨询

### ISSUE THREAD

**Issue by SUZILI7** [CrossmodalGroup/HREM#11]
EncoderImageAggr类中的
img_emb = self.opt.residual_weight * img_emb_res + (1 - self.opt.residual_weight) * img_emb
residual_weight 是怎么得到的，并没有在arguments里看到静态定义，他是动态的不断学习的吗，如果我想在其他模型运用类似方法，该如何使用？谢谢。

**Comment by darkpromise98** [comment]
首先，`residual_weight` 参数的定义在 `graph_lib.py` 文件里的`def extra_parameters` 函数中：
https://github.com/CrossmodalGroup/HREM/blob/main/graph_lib.py#L21

然后，在训练文件`train.py` 的开头，除了`arguments.py`里定义的参数，我们会引入额外定义的参数：
https://github.com/CrossmodalGroup/HREM/blob/main/train.py#L19-L22
