### ISSUE TITLE
Question Neighbor Batch Sampling

### ISSUE THREAD

**Issue by Minsky520** [CrossmodalGroup/HREM#4]
Hi, I would like to enquire about the part of  Neighbor Batch Sampling mentioned in the paper which seems to be missing from the code, can you tell why?

**Comment by darkpromise98** [comment]
According to our experiments, the proposed Neighbor Batch Sampling does not bring obvious performance improvements in two datasets, as described in the ablation study of the paper (Tab.3b, line 5). And the related implementation will bring addtional training time, so I delete this step (just use classical batch-sampling).
