### ISSUE TITLE
Questions about the code sequence

### ISSUE THREAD

**Issue by chauncey-tow** [CrossmodalGroup/HREM#5]
https://github.com/CrossmodalGroup/HREM/blob/d3c8298dbc068eea0b69e990f1b1e913d05893d3/lib/mca.py#L224
https://github.com/CrossmodalGroup/HREM/blob/d3c8298dbc068eea0b69e990f1b1e913d05893d3/lib/mca.py#L225

Hi @darkpromise98 , I notice this part in your paper is presented as follows:
![image](https://github.com/CrossmodalGroup/HREM/assets/59754670/0b9bd0ca-41c8-4f9b-be70-ba158f1d07c0)
I think your code I pinned on the top does not match with the paper. Should it correctly be as follows?

 batch_sim_t2t = torch.matmul(cap_emb, cap_emb.t()) 
 batch_sim_i2i = torch.matmul(img_emb, img_emb.t())

**Comment by darkpromise98** [comment]
Yes, you are right. Thanks for reminding me to fix the mistake.

**Comment by chauncey-tow** [comment]
What a joyful chat! Also thank you for sharing your work.
