### ISSUE TITLE
Relation Interaction Mechanism

### ISSUE THREAD

**Issue by HanaHangLee** [CrossmodalGroup/HREM#8]
It seems like in this code repository, you've only implemented the Fusion mechanism architecture and there's no standalone mechanism, right?
![image](https://github.com/CrossmodalGroup/HREM/assets/121029238/37893463-fdd2-4533-86c8-82cc7e36f6fe)

**Comment by darkpromise98** [comment]
Yes, you are right. We only release the **fusion mechanism** architecture since it is simpler and better than the standalone architecture. The core functions of these two architecture are the same.
