### ISSUE TITLE
能否告诉我数据集data文件在HREM-main下如何设置default和运行代码

### ISSUE THREAD

**Issue by SUZILI7** [CrossmodalGroup/HREM#9]
FileNotFoundError: [Errno 2] No such file or directory: 'data/f30k_precomp\\train_caps.txt'

**Comment by darkpromise98** [comment]
the 'data/f30k_precomp/train_caps.txt' can be downloaded in https://www.kaggle.com/datasets/kuanghueilee/scan-features/data

**Comment by SUZILI7** [comment]
代码在运行的时候没有进度提示吗，控制台只输出了网络结构

**Comment by darkpromise98** [comment]
We have the training logs, as shown in https://drive.google.com/file/d/1FcCGd_s31Y-S9LgXh0an8HiIVW0RjoXX/view?usp=sharing
